spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_spring_api
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect