spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customers
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  docker:
    compose:
      lifecycle-management: start_only
      file: ../my-spring-api/compose.yaml